Rails.application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  # Root path - temporary for testing
  root to: 'templates#index'
  
  # Authentication routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # Resources (generated by scaffold)
  resources :alunos
  resources :professors
  resources :administradors
  resources :disciplinas
  resources :turmas
  resources :templates do
    resources :perguntas, only: [:new, :create]
  end
  resources :formularios
  resources :perguntas
  resources :respostas
  
  # Namespace routes for different user types
  namespace :aluno do
    get "dashboard/index"
    get 'dashboard', to: 'dashboard#index'
  end
  
  namespace :professor do
    get 'dashboard', to: 'dashboard#index'
  end
  
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end
  
  # Custom routes for form answering
  resources :formularios do
    member do
      get 'responder'
      post 'enviar_respostas'
    end
  end
  
  # Health check route (good practice)
  get "up" => "rails/health#show", as: :rails_health_check
end