# Gemfile
source "https://rubygems.org"

# Core Rails
gem "rails"
gem "propshaft"
gem "sqlite3"
gem "puma"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "bcrypt"
gem "tzinfo-data", platforms: %i[windows jruby]

# Caching & Performance
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "thruster", require: false

# Testing (TDD)
gem "rspec-rails"
gem "factory_bot_rails"
gem "faker"
gem "shoulda-matchers"

#Verificações
gem 'simplecov', require: false, group: :test
gem "rubycritic", require: false
gem "rdoc", require: false
gem "metric_fu-Saikuro", require: false
gem "flog"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  # BDD - Cucumber
  gem "cucumber-rails", require: false
  
  # Test dependencies
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "database_cleaner"
  gem "simplecov", require: false
  gem "rails-controller-testing"
end