source "https://rubygems.org"

# Rails core
gem "rails", "~> 8.0.4"

# Asset pipeline
gem "propshaft"

# Database
gem "sqlite3", ">= 2.1"

# Web server
gem "puma", ">= 5.0"
gem "thruster", require: false

# Hotwire/JavaScript
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

# API
gem "jbuilder"

# Authentication
gem "bcrypt"

# Caching and background jobs
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Performance
gem "bootsnap", require: false

# Timezone
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  # Testing
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers", "~> 5.0"
  gem "cucumber-rails", require: false
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "database_cleaner"
  gem "simplecov", require: false
  gem "rails-controller-testing"
  
  # Debugging
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  
  # Code quality
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end